apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-service

  template:

    metadata:
      labels:
        app: api-service

    spec:

      containers:

      - name: api-service

        image: adityalahkar/api-service:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:

        - name: REDIS_HOST
          value: redis

        - name: REDIS_PORT
          value: "6379"

        volumeMounts:

        - name: shared-storage
          mountPath: /uploads

        - name: shared-storage
          mountPath: /processed

      volumes:

      - name: shared-storage

        persistentVolumeClaim:
          claimName: shared-storage-pvc
